# AI 데이터 분석 비서 - Docker Compose 설정

version: '3.8'

services:
  # PostgreSQL 데이터베이스
  postgres:
    image: postgres:15
    container_name: ai_analyst_db
    environment:
      POSTGRES_DB: ai_analyst
      POSTGRES_USER: ai_user
      POSTGRES_PASSWORD: ai_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    networks:
      - ai_analyst_network

  # Redis 캐시
  redis:
    image: redis:7-alpine
    container_name: ai_analyst_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - ai_analyst_network

  # AI 분석 애플리케이션 (개발용)
  app:
    build: .
    container_name: ai_analyst_app
    ports:
      - "7860:7860"
    environment:
      - DATABASE_URL=postgresql://ai_user:ai_password@postgres:5432/ai_analyst
      - REDIS_URL=redis://redis:6379/0
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DEBUG=True
    depends_on:
      - postgres
      - redis
    volumes:
      - ./app:/app/app
      - ./uploads:/app/uploads
    networks:
      - ai_analyst_network
    # 개발 중에는 주석 처리
    # command: python app/main.py

volumes:
  postgres_data:
  redis_data:

networks:
  ai_analyst_network:
    driver: bridge
